### ISSUE TITLE
Old/deleted projects stills how up in search results

### ISSUE THREAD

**Issue by thinkcube-solutions** [brpaz/ulauncher-vscode-projects#17]
Hello,

How do you clean out old projects? I have folders/projects that do not exist anymore but they still show up in this extension's search results. I tried clearing the contents of ~/.config/Code/User/globalStorage/alefragnani.project-manager/ but that does not change anything.

Thank you!

**Comment by brpaz** [comment]
Do you mean recent workspaces or folders from the project manager extension (blue folder icon vs Code icon)? If it´s the latter it should be fixed on the latest commit.

**Comment by thinkcube-solutions** [comment]
Hi, @brpaz Yes that is correct. Okay, thanks! I will test out the latest version and let you know.

**Comment by thinkcube-solutions** [comment]
Hi, @brpaz Sorry for the late reply. Just got to finally testing this. The latest commit does indeed fix that issue. Thanks again for all your work and the wonderful project.
