### ISSUE TITLE
Add support for Insiders Edition

### ISSUE THREAD

**Issue by aitorllj93** [brpaz/ulauncher-vscode-projects#4]
Visual Studio command can't be changed so I can't use Visual Studio Code Insiders to open projects

**Comment by therj** [comment]
> Visual Studio command can't be changed so I can't use Visual Studio Code Insiders to open projects

This should work fine
`code-insiders dirname` 
vs
`code dirname`

**Comment by brpaz** [comment]
VS Code command could be configurable in the extension settings. PRs are welcome.

**Comment by brpaz** [comment]
I have added a new setting to the extension allowing to specify the path to the VS Code executable.
It defaults to "code" but change to "code-insiders" should work.
