### ISSUE TITLE
There's an error in manifest.json:  'required_api_version' is not provided

### ISSUE THREAD

**Issue by frommMoritz** [brpaz/ulauncher-vscode-projects#6]
With the newest ulauncher version the extension does not load.

```
There's an error in manifest.json: 
'required_api_version' is not provided

Try updating the extension. If the doesn't help let the author know about this problem via Github issues.
```

This seems to be an issue with the new extensions API. Details on how to upgrade may be found here: http://docs.ulauncher.io/en/latest/extensions/migration.html

**Comment by brpaz** [comment]
I plan to migrate all my extensions to the new API. PRs are welcome.

**Comment by frommMoritz** [comment]
I will take a look at it after my exams. In the documentation it seems to be pretty straightforward.

**Comment by brpaz** [comment]
MIgration is Done.
